class ErrorTypes:
    VALIDATION_ERROR = "VALIDATION_ERROR"
    SERVER_ERROR = "SERVER_ERROR"
    UNAUTHORIZED_ERROR = "UNAUTHORIZED_ERROR"
    NOT_FOUND_ERROR = "NOT_FOUND_ERROR"

class StatusCodes:
    SUCCESS = 200
    CREATED = 201
    ACCEPTED = 202
    BAD_REQUEST = 400
    UNAUTHORIZED = 401
    FORBIDDEN = 403
    NOT_FOUND = 404
    INTERNAL_SERVER_ERROR = 500